# Generated by Django 4.2.1 on 2023-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_jogo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('plataforma_jogo', models.CharField(choices=[('PS3', 'Playstation 3'), ('PS4', 'Playstation 4'), ('PS5', 'Playstation 5'), ('PC', 'Pc')], default='PS4', max_length=3)),
                ('lancamento', models.DateField()),
                ('distribuidora', models.CharField(max_length=100)),
                ('genero_jogo', models.CharField(choices=[('ACAO', 'Ação'), ('AVENTURA', 'Aventura'), ('ARCADE', 'Arcade'), ('TIRO', 'Tiro'), ('RPG', 'RPG'), ('SIMULACAO', 'Simulação'), ('ESPORTE', 'Esporte'), ('CORRIDA', 'Direção/Corrida'), ('TERROR', 'Terror')], default='', max_length=10)),
                ('classificacao', models.CharField(choices=[('L', 'para todas as idades'), ('10', 'Classificação 10+'), ('12', 'Classificação 12+'), ('14', 'Classificação 14+'), ('16', 'Classificação 16+'), ('18', 'Classificação 18+')], default='', max_length=2)),
                ('voz', models.CharField(blank=True, choices=[('EN', 'Inglês'), ('BR', 'Português Brasil'), ('ES', 'Espanhol')], max_length=2, null=True)),
                ('preco', models.FloatField()),
                ('imagem', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
